<?php
/**
 * @FileID: DOC_GEN_001
 * @Module: Documentation
 * @Author: Nefi
 * @LastModified: 2025-11-21
 * @SecurityTag: validated
 */

// Simple Markdown to HTML converter
function markdownToHtml($markdown) {
    // Headers
    $html = preg_replace('/^# (.*?)$/m', '<h1>$1</h1>', $markdown);
    $html = preg_replace('/^## (.*?)$/m', '<h2>$1</h2>', $html);
    $html = preg_replace('/^### (.*?)$/m', '<h3>$1</h3>', $html);
    
    // Bold and Italic
    $html = preg_replace('/\*\*(.*?)\*\*/', '<strong>$1</strong>', $html);
    $html = preg_replace('/\*(.*?)\*/', '<em>$1</em>', $html);
    
    // Code blocks
    $html = preg_replace('/```(.*?)```/s', '<pre><code>$1</code></pre>', $html);
    $html = preg_replace('/`(.*?)`/', '<code>$1</code>', $html);
    
    // Lists
    $html = preg_replace('/^\* (.*?)$/m', '<li>$1</li>', $html);
    $html = preg_replace('/(<li>.*<\/li>)/s', '<ul>$1</ul>', $html);
    // Fix nested lists (simple fix)
    $html = preg_replace('/<\/ul>\s*<ul>/', '', $html);
    
    // Paragraphs (double newline)
    $html = preg_replace('/\n\n/', '<br><br>', $html);
    
    return $html;
}

function generateHtmlDoc($inputFile, $outputFile, $title) {
    $markdown = file_get_contents($inputFile);
    
    // Remove metadata block
    $markdown = preg_replace('/\/\*\*.*?\*\/\s*/s', '', $markdown);
    
    $content = markdownToHtml($markdown);
    
    $template = <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>$title - MPHS Job Application System</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 0; background-color: #f4f4f9; }
        .container { max-width: 900px; margin: 0 auto; padding: 20px; background: #fff; box-shadow: 0 2px 5px rgba(0,0,0,0.1); min-height: 100vh; }
        header { background: #2c3e50; color: #fff; padding: 20px; text-align: center; }
        header h1 { margin: 0; font-size: 24px; }
        nav { background: #34495e; padding: 10px; text-align: center; }
        nav a { color: #fff; text-decoration: none; margin: 0 15px; font-weight: bold; }
        nav a:hover { text-decoration: underline; }
        h1, h2, h3 { color: #2c3e50; }
        h1 { border-bottom: 2px solid #eee; padding-bottom: 10px; }
        h2 { margin-top: 30px; border-bottom: 1px solid #eee; padding-bottom: 5px; }
        code { background: #f8f9fa; padding: 2px 5px; border-radius: 3px; font-family: Consolas, monospace; color: #e74c3c; }
        pre { background: #f8f9fa; padding: 15px; border-radius: 5px; overflow-x: auto; border: 1px solid #eee; }
        pre code { color: #333; background: none; padding: 0; }
        ul { padding-left: 20px; }
        li { margin-bottom: 5px; }
        footer { text-align: center; padding: 20px; color: #777; font-size: 14px; border-top: 1px solid #eee; margin-top: 40px; }
    </style>
</head>
<body>
    <header>
        <h1>MPHS Job Application System Documentation</h1>
    </header>
    <nav>
        <a href="index.html">Home</a>
        <a href="user_guide.html">User Guide</a>
        <a href="technical_reference.html">Technical Reference</a>
        <a href="developer_guide.html">Developer Guide</a>
    </nav>
    <div class="container">
        $content
    </div>
    <footer>
        &copy; 2025 Majlis Perbandaran Hulu Selangor. Generated by Documentation Module.
    </footer>
</body>
</html>
HTML;

    if (!is_dir(dirname($outputFile))) {
        mkdir(dirname($outputFile), 0777, true);
    }
    
    file_put_contents($outputFile, $template);
    echo "Generated: $outputFile\n";
}

// Define paths
$baseDir = __DIR__;
$htmlDir = $baseDir . '/html';

// Generate Docs
generateHtmlDoc($baseDir . '/User_Guide.md', $htmlDir . '/user_guide.html', 'User Guide');
generateHtmlDoc($baseDir . '/Technical_Reference.md', $htmlDir . '/technical_reference.html', 'Technical Reference');
generateHtmlDoc($baseDir . '/Developer_Guide.md', $htmlDir . '/developer_guide.html', 'Developer Guide');

// Generate Index
$indexContent = <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Documentation Hub - MPHS Job Application System</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 0; background-color: #f4f4f9; }
        .container { max-width: 900px; margin: 50px auto; padding: 40px; background: #fff; box-shadow: 0 2px 10px rgba(0,0,0,0.1); border-radius: 8px; text-align: center; }
        h1 { color: #2c3e50; margin-bottom: 10px; }
        p { color: #666; margin-bottom: 40px; }
        .card-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; }
        .card { background: #fff; border: 1px solid #eee; border-radius: 8px; padding: 20px; transition: transform 0.2s, box-shadow 0.2s; text-decoration: none; color: inherit; display: block; }
        .card:hover { transform: translateY(-5px); box-shadow: 0 5px 15px rgba(0,0,0,0.1); border-color: #3498db; }
        .card h2 { color: #3498db; margin-top: 0; font-size: 20px; }
        .card p { font-size: 14px; margin-bottom: 0; }
        .icon { font-size: 40px; margin-bottom: 15px; display: block; }
    </style>
</head>
<body>
    <div class="container">
        <h1>MPHS Job Application System</h1>
        <p>Welcome to the documentation hub. Select a guide below to get started.</p>
        
        <div class="card-grid">
            <a href="user_guide.html" class="card">
                <span class="icon">👥</span>
                <h2>User Guide</h2>
                <p>How to apply, check status, and manage your application.</p>
            </a>
            
            <a href="technical_reference.html" class="card">
                <span class="icon">⚙️</span>
                <h2>Technical Reference</h2>
                <p>System architecture, database schema, and configuration.</p>
            </a>
            
            <a href="developer_guide.html" class="card">
                <span class="icon">💻</span>
                <h2>Developer Guide</h2>
                <p>Code structure, API endpoints, and extension guides.</p>
            </a>
        </div>
    </div>
</body>
</html>
HTML;

file_put_contents($htmlDir . '/index.html', $indexContent);
echo "Generated: $htmlDir/index.html\n";

?>
